name: Deploy to GitHub Pages
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push :
    branches:
      -main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency : ci-${{github.ref}}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
        # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
   
      - name: Install dependencies
        run: npm install  # if you have dependencies, otherwise skip this step

      - name: Build the project
        run: npm run build  # or the build command for your project

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # directory to publish (update according to your project structure)
